[Parameters]
# Advance_in_time can be SolveDiffusion or SolveFilter
Advance_in_time=SolveFilter
#Advance_in_time=SolveDiffusion
#full_or_horizontal=full
#full_or_horizontal=horizontal

[Directories]
Slab2_Age_Dir=/Volumes/STORE01/Rhea/Slab2/Slab_Age_Grids/
Orig_Slabs2_grids_dir=/Volumes/STORE01/Rhea/Slab2/
New_grids_dir=/Volumes/STORE01/Rhea/Slab2/New_grids/
Contours_Slab_dir=/Volumes/STORE01/Rhea/Slab2/Slab2_CONTOURS/
XY_dir=/Volumes/STORE01/Rhea/Slab2/Slab2Clips/
age_grid=/Volumes/STORE01/Rhea/alisic/Rhea_input/Age_grids/new_age_042811.grd
topo_grid=/Users/gurnis/Desktop/Gurnis_Files/Working/Data_Sets/Large_Topo_and_Gravity_Files/etopo2.grd
dir_old_margins=/Users/gurnis/Desktop/Gurnis_Files/Working/Current_Work/Rhea_global_runs/Plate_Margins/NewDataSet
EHB_Catalog=/Users/gurnis/Desktop/Gurnis_Files/Working/Data_Sets/Earthquake_Catelogs/ISC_Catalogs/EHB_1960_2008.dat
rhea_depths=/Users/gurnis/Desktop/Gurnis_Files/Working/Current_Work/Rhea_global_runs/Rhea2/Rhea_meshes/shell_k2_ll5678_2016-03/depth_listing-l5678.dat
profile_dir=/Users/gurnis/Desktop/Gurnis_Files/Working/Current_Work/Rhea_global_runs/Slab2.0/Profiles/
global_convergence_grd_file=/Users/gurnis/Desktop/Gurnis_Files/Working/Current_Work/Rhea_global_runs/Convergence_Velocity/convergence_extrapolated.grd
tomo_dir=/Volumes/STORE01/Rhea/Tomography/LLNL_k2_l5678/
slab_temp_dir=/Users/gurnis/Desktop/Gurnis_Files/Working/Current_Work/Rhea_global_runs/Slab2.0/GRD_GLOBAL
tomo_name=LLNL
final_age_grid=/Volumes/STORE01/Rhea/Cratons_Tectonic_Regionalization/Sonja/new_age_050_125_300_5-5-16.grd
